### PR TITLE
We cannot indent paragraph which has less than two lines.

### LINKED ISSUE #12: IndexError: list index out of range
```
 Traceback (most recent call last):
  File "~/.local/share/gedit/plugins/reflow.py", line 87, in on_reflow_text_activate
    text = self._fill(before_text)
  File "~/.local/share/gedit/plugins/reflow.py", line 104, in _fill
    first_prefix = splits[0][0]
IndexError: list index out of range
```

### PR DESCRIPTION
**Pull request by mcepl**
Fixes #12

@guillaumechereau , are you even willing to do a code review for the changes, or should I just pretend you don’t exist?

### CODE REVIEW

**Comment by guillaumechereau** [comment]
On Mon, Aug 17, 2015 at 03:08:16AM -0700, Matěj Cepl wrote:
> changes, or should I just pretend you don’t exist?

Hi Matěj.  Sorry, I don't really maintain this project anymore since I
don't use gedit now.  I gave you write access, so feel free to commit
your changes.  I have to say I wouldn't mind you becoming the new
official maintainer of the plugin if you are interested.

Regards,
Guillaume

**Comment by mcepl** [comment]
> I have to say I wouldn't mind you becoming the new official maintainer of the plugin if you are interested.

Sure thing ... could you please go to Settings of the repo and Transfer it to me? I would love to get all history of issues, pull requests, etc. I will probably then move the whole thing to `gitlab.com`, but this way I could get whole thing. Thank you for the code anyway.

**Comment by guillaumechereau** [comment]
On Mon, Aug 17, 2015 at 04:22:17AM -0700, Matěj Cepl wrote:
> > I have to say I wouldn't mind you becoming the new official
> > maintainer of the plugin if you are interested.
> 
> Sure thing ... could you please go to Settings of the repo and
> Transfer it to me? I would love to get all history of issues, pull
> requests, etc. I will probably then move the whole thing to
> `gitlab.com`, but this way I could get whole thing. Thank you for the
> code anyway.

Why even bother?  The project is super small, pretty much stable, and
I already gave you full access to the repo.  No need to move things
around.

**Comment by mcepl** [comment]
> Why even bother? The project is super small, pretty much stable, and I already gave you full access to the repo. No need to move things around.

Never mind, gitlab was able to do it anyway ... the official repo is now https://gitlab.com/mcepl/gedit-reflow-plugin . Could you please at least add this URL to the description of this repository?

**Comment by guillaumechereau** [comment]
On Mon, Aug 17, 2015 at 05:34:56AM -0700, Matěj Cepl wrote:
> > Why even bother? The project is super small, pretty much stable, and
> > I already gave you full access to the repo. No need to move things
> > around.
> Never mind, gitlab was able to do it anyway ... the official repo is
> now https://gitlab.com/mcepl/gedit-reflow-plugin . Could you please at
> least add this URL to the description of this repository?

Matěj, I don't mind that much that you now take care of the plug-in, but
I am a bit disappointed by your decision to fork the project entirely,
move it to a new hosting place, and then declare that it is now the
'official' plug-in.  I don't see *ANY* reason why you think this was the
right thing to do.  Mind to explain?

**Comment by mcepl** [comment]
> Matěj, I don't mind that much that you now take care of the plug-in, but I am a bit disappointed by your decision to fork the project entirely, move it to a new hosting place, and then declare that it is now the 'official' plug-in. I don't see *ANY* reason why you think this was the right thing to do. Mind to explain?

Because I believed that was exactly what you proposed?

>> Sorry, I don't really maintain this project anymore since I don't use gedit now. I have to say I wouldn't mind you becoming the new official maintainer of the plugin if you are interested.

Why in the world I should maintain the repo in `/guillaumechereau/` namespace? What's the difference? Do you feel I should explain in `README` that you are the original author? Or what's the problem?

Besides, I believe that I have described in details exactly what I was planning to do and I haven't heard any objections to it. What did I miss?

I am sorry, I really understood that you gave up on whole gedit and that I should take over the project.

**Comment by guillaumechereau** [comment]
On Mon, Aug 17, 2015 at 07:59:53AM -0700, Matěj Cepl wrote:
> Do you feel I should explain in
> `README` that you are the original author? Or what's the problem?
Yes, please do so.  And also revert the link in the gnome wiki not to
point to your fork, you have no authority to claim it as the official
version.

**Comment by mcepl** [comment]
> Yes, please do so. And also revert the link in the gnome wiki not to point to your fork, you have no authority to claim it as the official version.

Done.

Au dieu.

**Pull request merged**
